### ISSUE TITLE
Are multiline AIS messages always send in order?

### ISSUE THREAD

**Issue by rvt** [dgiardini/rtl-sdr-misc#39]
Hey,

if we enable two channels, ais it guaranteed that multiline AIS messages are send in order and without being 'interrupted' by the other channel?

For example:

```
!AIVDM,3,1,8,A,8h30otA?0@<o;NPPPP<i>nskl4tSp1m>@00o;NPPPP<iCnsm<4tPG286@00o;NPP,0*3D
!AIVDM,3,2,8,A,PP<j>nsphTtHBR7@@00o;NPPPP<jCnssG4tCk2N0@00o;NPPPP<k>nsuPTt6m2Mt,0*44
<-- is it guaranteed no message of the other channel will appear here?
!AIVDM,3,3,8,A,@00o;NPPPP<kCnsuwTt3?2lB@00,2*3D
```

**Comment by dgiardini** [comment]
From the receiver side there is no such guarantee; the messages are decoded
while arriving, using two independent decoders, one for each channel.
